language: java
jdk:
  - oraclejdk8
sudo: required
install:
  - wget http://update.rascal-mpl.org/console/rascal-shell-unstable.jar 
  - sudo mv rascal-shell-unstable.jar /usr/local/bin/rascal.jar
  - sudo mv support/bin/rascal /usr/local/bin/rascal
  - sudo chmod +x /usr/local/bin/rascal
script:
  - cd src && rascal Tests
