version: 2
jobs:
  build:
    docker:
      - image: yoangrigorov/glagol-dsl-builds:latest
    working_directory: ~/repo
    environment:
      RASCAL_JAR: /usr/local/src/rascal-shell-unstable.jar
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mkdir /usr/local/src/
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${CIRCLE_TAG}-SNAPSHOT
      - run: build/get_rascal
      - run: build/build
      - run: mvn clean package
      - run: build/glagol test
      - run: if [[ ! -z ${CIRCLE_TAG} ]]; then github-release release --user bulgariaphp --repo glagol-dsl --tag ${CIRCLE_TAG} --name "${CIRCLE_TAG}" --description "Release ${CIRCLE_TAG}"; fi
      - run: if [[ ! -z ${CIRCLE_TAG} ]]; then github-release upload --user bulgariaphp --repo glagol-dsl --tag ${CIRCLE_TAG} --name "glagol-dsl-server-${CIRCLE_TAG}.jar" --file target/glagol-dsl.jar; fi
      - run: |
          TAG="latest"
          if [[ ! -z ${CIRCLE_TAG} ]]; then TAG=${CIRCLE_TAG}; TAG_MAJOR=${TAG:0:3} fi
          cp target/glagol-dsl.jar docker/glagol-dsl.jar
          docker build -t glagol/server:${TAG} -t glagol/server:${TAG_MAJOR} docker/
          docker login -u ${DOCKER_ID} -p ${DOCKER_SECRET}
          docker push glagol/server:${TAG}
          if [[ ! -z ${TAG_MAJOR} ]]; then docker push glagol/server:${TAG_MAJOR}; fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^ignore-.*/