version: 2
jobs:
  build:
    docker:
      - image: yoangrigorov/glagol-dsl-builds:latest
    working_directory: ~/repo
    environment:
      RASCAL_JAR: /usr/local/src/rascal-shell-unstable.jar
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${CIRCLE_TAG}-SNAPSHOT
      - run: mkdir /usr/local/src/
      - run: build/get_rascal
      - run: build/build
      - run: mvn clean package
      - run: build/glagol test
      - run: rm -rf library/Test library/Tests.rsc
      - run: mvn clean package
      - run:
          name: Making a GitHub Release
          command: |
            if [[ ! -z ${CIRCLE_TAG} ]]; then github-release release --user glagol-dsl --repo glagol-dsl --tag ${CIRCLE_TAG} --name "${CIRCLE_TAG}" --description "Release ${CIRCLE_TAG}"; fi; \
            if [[ ! -z ${CIRCLE_TAG} ]]; then github-release upload --user glagol-dsl --repo glagol-dsl --tag ${CIRCLE_TAG} --name "glagol-dsl-server-${CIRCLE_TAG}.jar" --file target/glagol-dsl.jar; fi;
      - run:
          name: Publishing Docker Hub images
          command: |
            cp target/glagol-dsl.jar docker/glagol-dsl.jar
            TAG="dev-master"
            if [[ ! -z ${CIRCLE_TAG} ]]; then TAG=${CIRCLE_TAG}; fi
            docker build -t glagol/server:${TAG} -t glagol/server:latest docker/
            docker login -u ${DOCKER_ID} -p ${DOCKER_SECRET}
            docker push glagol/server:${TAG}
            if [[ ! -z ${CIRCLE_TAG} ]]; then \
              TAG=${TAG:0:3}; \
              docker build -t glagol/server:${TAG} docker/ ; \
              docker push glagol/server:${TAG}; \
              docker push glagol/server:latest; \
            fi
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  deploy-gkp:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/repo
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Set Google Cloud Platform Access
          command: |
            gcloud --quiet components update  # remove if using the google/cloud-sdk image
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - checkout
      - run:
          name: Create Kubernetes Deployment
          command: kubectl apply deployment -f .gkp/deploy.yml --record
      - run:
          name: Create Kubernetes Service
          command: kubectl apply -f .gkp/service.yml
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^ignore-.*/
      - deploy-gkp:
          filters:
            tags:
              ignore: /^ignore-.*/