apiVersion: v1
kind: Service
metadata:
  name: glagol-server-svc
  labels:
    app: glagol-server
spec:
  type: ClusterIP
  ports:
  - port: 51151
    protocol: TCP
  selector:
    app: glagol-server
